title = "Velocitas"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same lang as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]


# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-130444728-1"

# Language configuration

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print", "RSS"]

[params]
copyright = "The Eclipse Velocitas™ Project"
# privacy_policy = "https://eclipse.org/legal/privacy.php"
  url = "https://eclipse.org/legal/copyright.php"
  name = "Copyright Agent"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
# version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "latest"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.


# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/eclipse-velocitas/velocitas-docs"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/eclipse-velocitas"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = true
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
# Set to true to make the sidebar foldable
sidebar_menu_foldable = true
# Uncomment to specify a fixed unfold depth
# sidebar_menu_unfold_depth = 1

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
    name = "Eclipse Velocitas Project"
    url = "https://projects.eclipse.org/projects/automotive.velocitas"
    icon = "fas fa-external-link-alt"
    desc = "Eclipse Velocitas project home page"
[[params.links.user]]
    name = "Developer mailing list"
    url = "https://accounts.eclipse.org/mailing-list/velocitas-dev"
    icon = "fa fa-envelope"
    desc = "Eclipse Velocitas developer discussions"
[[params.links.user]]
    name ="Twitter"
    url = "https://twitter.com/velocitas_sdv"
    icon = "fab fa-twitter"
    desc = "Follow us on Twitter to get the latest news!"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
    name = "GitHub"
    url = "https://github.com/eclipse-velocitas"
    icon = "fab fa-github"
    desc = "Eclipse Velocitas GitHub organization"

# Eclipse relevant links. These will show up at the bottom footer line.
[[params.links.eclipse]]
  url = "https://eclipse.org"
  name = "Eclipse Foundation"

[[params.links.eclipse]]
  url = "https://eclipse.org/legal/privacy.php"
  name = "Privacy Policy"

[[params.links.eclipse]]
  url = "https://eclipse.org/legal/termsofuse.php"
  name = "Terms of Use"

[[params.links.eclipse]]
  url = "https://eclipse.org/legal/copyright.php"
  name = "Copyright Agent"

[[params.links.eclipse]]
  url = "https://eclipse.org/legal/"
  name = "Legal"

[[params.links.eclipse]]
  url = "https://eclipse.org/legal/epl-2.0/"
  name = "License"

[[params.links.eclipse]]
  url = "https://eclipse.org/security/"
  name = "Report a Vulnerability"

# Additional menu items
[[menu.main]]
identifier = "GitHub"
name = "GitHub"
url = "https://github.com/eclipse-velocitas"
weight = 60

[params.drawio]
enable = true
#drawio_server = "https://example.com/"

# For a full list of parameters used in Docsy sites, see:
# https://github.com/google/docsy-example/blob/master/config.toml

[outputFormats]
[outputFormats.PRINT]
baseName = "index"
isHTML = true
mediaType = "text/html"
path = "_print"
permalinkable = false

[module]
[module.hugoVersion]
extended = true
min = "0.73.0"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'node_modules/bootstrap'
    target = 'assets/vendor/bootstrap'
  [[module.mounts]]
    source = 'node_modules/@fortawesome/fontawesome-free'
    target = 'assets/vendor/Font-Awesome'
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = "../docs/pythonsdk"
    target = "content/docs/python-sdk"
    lang = "en"

