@startuml
participant VAPP as "Vehicle Application"
participant vehicle_data_broker as "Vehicle Data Broker"
participant vehicle_service as "Vehicle Service (e.g. seat service)"
participant hardware_abstraction as "Hardware Abstraction"
participant can_network as "CAN Network"


VAPP -> vehicle_service: Request using gRPC service to change seat position
vehicle_service <-> hardware_abstraction: Exchange data points as specified by service implementation and DBC file
can_network <-> hardware_abstraction: Exchange data points as specified in DBC file
vehicle_service -> vehicle_data_broker: Publish data as specified by service implementation
VAPP <- vehicle_service: Return operation result

@enduml