name: ❓ Question
description: Share a question about W&B
title: "[Q]: "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        **We are happy that you have a question to ask!**
  - type: textarea
    validations:
      required: true
    attributes:
      label: Question
      description: Tell us how can we help to you
      placeholder: How can I create template repository?
