
# /********************************************************************************
# Copyright (c) 2022 Robert Bosch GmbH and Microsoft Corporation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: CI workflow

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  Build-documentation:
    runs-on: ubuntu-latest
    name: Building documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: "0.110.0"
          extended: true

      - name: Build
        run: |
          export NODE_PATH=$NODE_PATH:`npm root -g`
          npm i -g postcss postcss-cli autoprefixer
          echo "Build documentation for GitHub Pages"
          hugo --baseURL /velocitas

      - name: Fixes
        run: |
          for f in public/docs/index.html public/docs/_print/index.html; do sed -i 's,/docs/contributing/contribution,/velocitas/docs/contributing/contribution,g' $f; done

      - name: Check
        continue-on-error: true
        run: |
          echo $(docker run -v $(pwd)/public:/public -v $(pwd)/.htmltest.yml:/.htmltest.yml --rm wjdp/htmltest -s /public -c /.htmltest.yml) >> $GITHUB_STEP_SUMMARY
      
      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh_pages
