@startuml
participant VAPP as "Vehicle Application"
participant vehicle_data_broker as "Vehicle Data Broker"
participant data_feeder as "Data Feeder (e.g. CAN Feeder)"
participant hardware_abstraction as "Hardware Abstraction"
participant can_network as "CAN Network"


VAPP -> vehicle_data_broker: Request using gRPC service to read/write/subscribe date points
can_network <-> hardware_abstraction: Exchange data points as specified in DBC file
data_feeder <-> hardware_abstraction: Exchange data points as specified in DBC file 
data_feeder <-> vehicle_data_broker: Exchange data points as specified in Yaml mapping file
VAPP <- vehicle_data_broker: Datapoints returned by gRPC

@enduml